In [4]:
list={"id":[1,2,3],"name":["shiva","ramu","shivu"],'Score': [85, 40, 75]}
list

{'id': [1, 2, 3], 'name': ['shiva', 'ramu', 'shivu'], 'Score': [85, 40, 75]}

In [5]:
import pandas as pd
df=pd.DataFrame(list)
df

   id   name  Score
0   1  shiva     85
1   2   ramu     40
2   3  shivu     75

In [8]:
df["result"]=df["Score"].apply(lambda x: "pass" if x>50 else "fail")
df

   id   name  Score result
0   1  shiva     85   pass
1   2   ramu     40   fail
2   3  shivu     75   pass

In [9]:
kinf=lambda x :x+2

40

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'Math': [50, 80],
    'Science': [70, 60]
})

# Find total marks for each row
df['Total'] = df.apply(lambda row: row['Math'] + row['Science'], axis=1)

print(df)