In [4]:
import pandas as pd 
df=pd.read_csv("stdebts_cleaning.csv")
print(df)

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\shiva\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 736, in start
    self.io_loop.start()
  File "C:\Users\shiva\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\shiva\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\shiva\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\shiva\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 516, in dispatch_queue
    await self.process_one()
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 505, in process_one
    await dispatch(*args)
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 412, in dispatch_shell
    await result
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 740, in execute_request
    reply_content = await reply_content
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 422, in do_execute
    res = shell.run_cell(
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 546, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\shiva\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3024, in run_cell
    result = self._run_cell(
  File "C:\Users\shiva\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3079, in _run_cell
    result = runner(coro)
  File "C:\Users\shiva\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\shiva\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3284, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\shiva\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3466, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\shiva\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\shiva\AppData\Local\Temp\ipykernel_26420\1433590514.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\shiva\anaconda3\Lib\site-packages\pandas\__init__.py", line 38, in <module>
    from pandas.compat import (
  File "C:\Users\shiva\anaconda3\Lib\site-packages\pandas\compat\__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "C:\Users\shiva\anaconda3\Lib\site-packages\pandas\compat\pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "C:\Users\shiva\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\shiva\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 736, in start
    self.io_loop.start()
  File "C:\Users\shiva\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\shiva\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\shiva\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\shiva\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 516, in dispatch_queue
    await self.process_one()
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 505, in process_one
    await dispatch(*args)
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 412, in dispatch_shell
    await result
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 740, in execute_request
    reply_content = await reply_content
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 422, in do_execute
    res = shell.run_cell(
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 546, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\shiva\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3024, in run_cell
    result = self._run_cell(
  File "C:\Users\shiva\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3079, in _run_cell
    result = runner(coro)
  File "C:\Users\shiva\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\shiva\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3284, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\shiva\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3466, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\shiva\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\shiva\AppData\Local\Temp\ipykernel_26420\1433590514.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\shiva\anaconda3\Lib\site-packages\pandas\__init__.py", line 61, in <module>
    from pandas.core.api import (
  File "C:\Users\shiva\anaconda3\Lib\site-packages\pandas\core\api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "C:\Users\shiva\anaconda3\Lib\site-packages\pandas\core\dtypes\dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "C:\Users\shiva\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\shiva\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 736, in start
    self.io_loop.start()
  File "C:\Users\shiva\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\shiva\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\shiva\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\shiva\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 516, in dispatch_queue
    await self.process_one()
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 505, in process_one
    await dispatch(*args)
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 412, in dispatch_shell
    await result
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 740, in execute_request
    reply_content = await reply_content
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 422, in do_execute
    res = shell.run_cell(
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 546, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\shiva\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3024, in run_cell
    result = self._run_cell(
  File "C:\Users\shiva\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3079, in _run_cell
    result = runner(coro)
  File "C:\Users\shiva\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\shiva\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3284, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\shiva\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3466, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\shiva\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\shiva\AppData\Local\Temp\ipykernel_26420\1433590514.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\shiva\anaconda3\Lib\site-packages\pandas\__init__.py", line 61, in <module>
    from pandas.core.api import (
  File "C:\Users\shiva\anaconda3\Lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\shiva\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\shiva\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\shiva\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 52, in <module>
    from pandas.core import (
  File "C:\Users\shiva\anaconda3\Lib\site-packages\pandas\core\ops\__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "C:\Users\shiva\anaconda3\Lib\site-packages\pandas\core\ops\array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "C:\Users\shiva\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "C:\Users\shiva\anaconda3\Lib\site-packages\pandas\core\computation\check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "C:\Users\shiva\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\shiva\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\shiva\anaconda3\Lib\site-packages\numexpr\__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\shiva\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 736, in start
    self.io_loop.start()
  File "C:\Users\shiva\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\shiva\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\shiva\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\shiva\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 516, in dispatch_queue
    await self.process_one()
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 505, in process_one
    await dispatch(*args)
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 412, in dispatch_shell
    await result
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 740, in execute_request
    reply_content = await reply_content
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 422, in do_execute
    res = shell.run_cell(
  File "C:\Users\shiva\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 546, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\shiva\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3024, in run_cell
    result = self._run_cell(
  File "C:\Users\shiva\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3079, in _run_cell
    result = runner(coro)
  File "C:\Users\shiva\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\shiva\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3284, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\shiva\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3466, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\shiva\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\shiva\AppData\Local\Temp\ipykernel_26420\1433590514.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\shiva\anaconda3\Lib\site-packages\pandas\__init__.py", line 61, in <module>
    from pandas.core.api import (
  File "C:\Users\shiva\anaconda3\Lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\shiva\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\shiva\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\shiva\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 66, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "C:\Users\shiva\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py", line 61, in <module>
    from pandas.core import (
  File "C:\Users\shiva\anaconda3\Lib\site-packages\pandas\core\nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "C:\Users\shiva\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\shiva\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\shiva\anaconda3\Lib\site-packages\bottleneck\__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

AttributeError: _ARRAY_API not found

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [6]:
df.iloc[1,1]=30

In [8]:
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False  False  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [14]:
df.isnull().sum()

Name         1
Age          2
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [4]:
df

NameError: name 'df' is not defined

In [50]:
df["Age"].fillna(df["Age"].mean())
print(df)

      Name        Age         City Gender              Email   Join Date
0    Alice  25.000000     New York      F  alice@example.com  01-05-2021
1  Charlie  30.000000        Delhi      M    charlie@example  20-07-2021
2      Bob  30.000000  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  26.428571        Delhi      M    charlie@example  20-07-2021
4    David  22.000000       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.000000        Delhi      F     eve@domain.com         NaN
6    Alice  25.000000     New York      F  alice@example.com  01-05-2021
7    Alice  25.000000     New York      F  alice@example.com  01-05-2021
8  Charlie  26.428571        Delhi      M    charlie@example  20-07-2021

In [43]:
for i in range(len(df)):
    if pd.isna(df.loc[i, "Age"]):
        df.loc[i, "Age"] = 23

In [20]:
s="python,java,c++,g0"
print(s.split(',',0))

['python,java,c++,g0']

In [25]:
df.dropna(axis=1)

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [26]:
df.dropna(axis=0) #is always equal to the drp original function

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021

In [3]:
df.ffill() #it will print the forword

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [4]:
df.bfill()#bfill it will fill the back of the no's it has a same ad the df.fillna(method="bfill")

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [16]:
import pandas as pd

# Read CSV
df = pd.read_csv("stdebts_cleaning.csv")

# New row data
new_row = {"Name": "Alice", "Age":30,"City":"New York","gender":"M","Email":"lice@example.com","Join Date":1-5-2021}

# Insert at line 2 (i.e., index 1)
df.loc[2] = new_row   # temporary index

# Reorder index
df = df.reset_index(drop=True)

# Save back to CSV
df.to_csv("data.csv", index=False)

print(df)

      Name   Age      City Gender              Email   Join Date
0    Alice  25.0  New York      F  alice@example.com  01-05-2021
1  Charlie   NaN     Delhi      M    charlie@example  20-07-2021
2    Alice  30.0  New York    NaN   lice@example.com       -2025
3  Charlie   NaN     Delhi      M    charlie@example  20-07-2021
4    David  22.0    Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0     Delhi      F     eve@domain.com         NaN
6    Alice  25.0  New York      F  alice@example.com  01-05-2021
7    Alice  25.0  New York      F  alice@example.com  01-05-2021
8  Charlie   NaN     Delhi      M    charlie@example  20-07-2021

In [27]:
print(df["Age"].duplicated().sum())

4

In [30]:
 df.drop_duplicates().reset_index() #reset index function it will reset the reset the indexes
    #it will remove the dublicated values

   index     Name   Age      City Gender              Email   Join Date
0      0    Alice  25.0  New York      F  alice@example.com  01-05-2021
1      1  Charlie   NaN     Delhi      M    charlie@example  20-07-2021
2      2    Alice  30.0  New York    NaN   lice@example.com       -2025
3      4    David  22.0    Mumbai      M  david@example.com  12-11-2019
4      5      NaN  28.0     Delhi      F     eve@domain.com         NaN

In [4]:
df.duplicated(subset=["Name","Age"])#it will cheak the copies no are the duplicted or not of the specific colomz

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [10]:
df["City"].str.lower() #it will convert the all string the into lower

0       new york
1          delhi
2    los angeles
3          delhi
4         mumbai
5          delhi
6       new york
7       new york
8          delhi
Name: City, dtype: object

In [13]:
df["Age"].drop()

ValueError: Need to specify at least one of 'labels', 'index' or 'columns'

In [37]:

df.dropna()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [14]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [16]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [30]:
df2=df.dropna()

In [58]:
df3=df.dropna()

In [34]:
df2["Age"]=df2["Age"].astype(float)
print(df2) #it will convert to the datatypes

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

C:\Users\shiva\AppData\Local\Temp\ipykernel_45548\3869283457.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Age"]=df2["Age"].astype(float)

In [49]:
import numpy as np

df2["Age group"] = np.where(df2["Age"] < 18, "child", "adalt")
print(df2)

    Name   Age         City Gender              Email   Join Date Age group
0  Alice  25.0     New York      F  alice@example.com  01-05-2021     adalt
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     adalt
4  David  22.0       Mumbai      M  david@example.com  12-11-2019     adalt
6  Alice  25.0     New York      F  alice@example.com  01-05-2021     adalt
7  Alice  25.0     New York      F  alice@example.com  01-05-2021     adalt

C:\Users\shiva\AppData\Local\Temp\ipykernel_45548\2974063318.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Age group"] = np.where(df2["Age"] < 18, "child", "adalt")

In [47]:
x = 5
result = ["Even" if x % 2 == 0 else "Odd"]
print(result)

['Odd']

In [65]:
df3["shia"]=["Adult" if x>18  else "adalt" for x in df3["Age"]]

C:\Users\shiva\AppData\Local\Temp\ipykernel_45548\4256342564.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3["shia"]=["Adult" if x>18  else "adalt" for x in df3["Age"]]

In [70]:
df3["Age group"] = ["Adult" if x > 18 else "child" for x in df3["Age"]]

C:\Users\shiva\AppData\Local\Temp\ipykernel_45548\1559117409.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3["Age group"] = ["Adult" if x > 18 else "child" for x in df3["Age"]]

In [71]:
print(df3)

    Name   Age         City Gender              Email   Join Date Age group  \
0  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
4  David  22.0       Mumbai      M  david@example.com  12-11-2019     Adult
6  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
7  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult

    shia
0  Adult
2  Adult
4  Adult
6  Adult
7  Adult

In [72]:
df2

    Name   Age         City Gender              Email   Join Date Age group
0  Alice  25.0     New York      F  alice@example.com  01-05-2021     adult
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     adult
4  David  22.0       Mumbai      M  david@example.com  12-11-2019     adult
6  Alice  25.0     New York      F  alice@example.com  01-05-2021     adult
7  Alice  25.0     New York      F  alice@example.com  01-05-2021     adult

In [78]:
fr=[]
for x in df2["Age group"]:
    fr.append(x.lower)
    print(x)
df2["small"]=fr

adult
adult
adult
adult
adult

C:\Users\shiva\AppData\Local\Temp\ipykernel_45548\4110060543.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["small"]=fr

In [4]:
import pandas as pd

# Define a function to apply
def my_function(x):
    return x * 2

# Example DataFrame
df = pd.DataFrame({'A': [1, 2, 3], 'B': [10, 20, 30]})

# Apply the function to each column (default axis=0)
result_col = df.apply(my_function)

# Apply the function to each row (axis=1)
result_row = df.apply(my_function, axis=0)

print("Apply function to each column:")
print(result_col)
print("\nApply function to each row:")
print(result_row)

Apply function to each column:
   A   B
0  2  20
1  4  40
2  6  60

Apply function to each row:
   A   B
0  2  20
1  4  40
2  6  60

In [88]:
import pandas as pd
data=pd.read_csv("films.csv")
df=pd.DataFrame(data)
print(df)

                 Actor                      Film  Year            Genre  \
0           Aamir Khan                    Dangal  2016        Biography
1          Salman Khan           Tiger Zinda Hai  2017           Action
2         Varun Dhawan     Badrinath Ki Dulhania  2017  Romantic Comedy
3        Ranveer Singh                 Padmaavat  2018       Historical
4   Ayushmann Khurrana                 Andhadhun  2018         Thriller
5        Rajkummar Rao                     Stree  2018    Horror Comedy
6       Hrithik Roshan                       War  2019           Action
7         Akshay Kumar                Good Newwz  2019           Comedy
8        Vicky Kaushal  Uri: The Surgical Strike  2019           Action
9        Ranbir Kapoor                Brahmastra  2022          Fantasy
10       Kartik Aaryan         Bhool Bhulaiyaa 2  2022    Horror Comedy
11      Shah Rukh Khan                   Pathaan  2023           Action

    BoxOffice(INR Crore)  IMDb
0                   2024   8.4
1                    565   6.0
2                    201   6.1
3                    585   7.0
4                    118   8.3
5                    180   7.5
6                    475   6.5
7                    318   7.0
8                    342   8.2
9                    431   5.6
10                   266   6.4
11                  1050   7.2

In [9]:
df["Year"].sort_values(ascending=False)

KeyError: 'Year'

In [7]:
df3=pd.DataFrame(df)
print(df3)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [8]:
df3=df3.drop_duplicates(subset=[""])

KeyError: Index(['Year'], dtype='object')

In [93]:
print(df3)

             Actor             Film  Year       Genre  BoxOffice(INR Crore)  \
0       Aamir Khan           Dangal  2016   Biography                  2024
1      Salman Khan  Tiger Zinda Hai  2017      Action                   565
3    Ranveer Singh        Padmaavat  2018  Historical                   585
6   Hrithik Roshan              War  2019      Action                   475
9    Ranbir Kapoor       Brahmastra  2022     Fantasy                   431
11  Shah Rukh Khan          Pathaan  2023      Action                  1050

    IMDb
0    8.4
1    6.0
3    7.0
6    6.5
9    5.6
11   7.2

In [95]:
print(df)

                 Actor                      Film  Year            Genre  \
0           Aamir Khan                    Dangal  2016        Biography
1          Salman Khan           Tiger Zinda Hai  2017           Action
2         Varun Dhawan     Badrinath Ki Dulhania  2017  Romantic Comedy
3        Ranveer Singh                 Padmaavat  2018       Historical
4   Ayushmann Khurrana                 Andhadhun  2018         Thriller
5        Rajkummar Rao                     Stree  2018    Horror Comedy
6       Hrithik Roshan                       War  2019           Action
7         Akshay Kumar                Good Newwz  2019           Comedy
8        Vicky Kaushal  Uri: The Surgical Strike  2019           Action
9        Ranbir Kapoor                Brahmastra  2022          Fantasy
10       Kartik Aaryan         Bhool Bhulaiyaa 2  2022    Horror Comedy
11      Shah Rukh Khan                   Pathaan  2023           Action

    BoxOffice(INR Crore)  IMDb
0                   2024   8.4
1                    565   6.0
2                    201   6.1
3                    585   7.0
4                    118   8.3
5                    180   7.5
6                    475   6.5
7                    318   7.0
8                    342   8.2
9                    431   5.6
10                   266   6.4
11                  1050   7.2

In [110]:
df.sort_values(["IMDb","Age","BoxOffice(INR Crore)"])

KeyError: 'Age'

In [81]:
print(df3)

None

In [3]:
df4=df.sort_values(["IMDb"],ascending=False).copy()

NameError: name 'df' is not defined

In [138]:
df4.reset_index()

,index,Actor,Film,Year,Genre,BoxOffice,IMDb,Rank
0,0,Aamir Khan,Dangal,2016,Biography,2024,8.4,8.4
1,4,Ayushmann Khurrana,Andhadhun,2018,Thriller,118,8.3,8.3
2,8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,8.2
3,5,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,7.5
4,11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,7.2
5,3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,7.0
6,7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,7.0
7,6,Hrithik Roshan,War,2019,Action,475,6.5,6.5
8,10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,6.4,6.4
9,2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,6.1
10,1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,6.0
11,9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,5.6

In [134]:
df4.sort_values('ascending=False)

0     8.4
4     8.3
8     8.2
5     7.5
11    7.2
3     7.0
7     7.0
6     6.5
10    6.4
2     6.1
1     6.0
9     5.6
Name: IMDb, dtype: float64

In [2]:
print(df4)

NameError: name 'df4' is not defined