In [20]:
import pandas as pd
df = pd.DataFrame({
    "Department": ["HR", "HR", "IT", "IT", "Marketing", "Marketing", "Sales", "Sales"],
    "Team": ["A", "A", "B", "B", "C", "C", "D", "D"],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F"],
    "Salary": [85, 90, 78, 85, 92, 88, 75, 80],
    "Age": [23, 25, 30, 22, 28, 26, 21, 27],
    "JoinDate": pd.to_datetime([
        "2020-01-10", "2020-02-15", "2021-03-20", "2021-04-10",
        "2020-05-30", "2020-06-25", "2021-07-15", "2021-08-01"
    ])
})  
print(df)

  Department Team Gender  Salary  Age   JoinDate
0         HR    A      M      85   23 2020-01-10
1         HR    A      F      90   25 2020-02-15
2         IT    B      M      78   30 2021-03-20
3         IT    B      F      85   22 2021-04-10
4  Marketing    C      M      92   28 2020-05-30
5  Marketing    C      F      88   26 2020-06-25
6      Sales    D      M      75   21 2021-07-15
7      Sales    D      F      80   27 2021-08-01

In [24]:
df.groupby("Team")["Salary"].mean()

Team
A    87.5
B    81.5
C    90.0
D    77.5
Name: Salary, dtype: float64

In [23]:
df.groupby("Gender")["Salary"].agg(['max','min'])

        max  min
Gender
F        90   80
M        92   75

In [25]:
df.groupby("Gender").agg({
  "Salary": "mean",
  "Age": "max"
})

        Salary  Age
Gender
F        85.75   27
M        82.50   30

In [26]:
df.groupby("Gender")["Salary"].agg(lambda x: x.sum()/len(x))#it will also find the mean

Gender
F    85.75
M    82.50
Name: Salary, dtype: float64

In [35]:
df.groupby(["Team","Gender"])["Salary"].mean()

Team  Gender
A     F         90.0
      M         85.0
B     F         85.0
      M         78.0
C     F         88.0
      M         92.0
D     F         80.0
      M         75.0
Name: Salary, dtype: float64

In [32]:
df.groupby(["Team", "Gender"])["Salary"].mean()

Team  Gender
A     F         90.0
      M         85.0
B     F         85.0
      M         78.0
C     F         88.0
      M         92.0
D     F         80.0
      M         75.0
Name: Salary, dtype: float64

In [36]:
df["Team Avg"] = df.groupby("Team")["Salary"].transform("mean")

In [37]:
df

  Department Team Gender  Salary  Age   JoinDate  Team Avg
0         HR    A      M      85   23 2020-01-10      87.5
1         HR    A      F      90   25 2020-02-15      87.5
2         IT    B      M      78   30 2021-03-20      81.5
3         IT    B      F      85   22 2021-04-10      81.5
4  Marketing    C      M      92   28 2020-05-30      90.0
5  Marketing    C      F      88   26 2020-06-25      90.0
6      Sales    D      M      75   21 2021-07-15      77.5
7      Sales    D      F      80   27 2021-08-01      77.5

In [42]:
import pandas as pd
data=pd.read_csv("Employee_Data.csv")
df=pd.DataFrame(data)
print(df)

  Employee_ID     Name Department  Age Gender Joining_Date  Salary  \
0        E001    Alice         HR   29      F   2020-05-12   48000
1        E002      Bob         IT   35      M   2018-07-01   65000
2        E003  Charlie    Finance   41      M   2015-03-23   72000
3        E004    Diana         IT   28      F   2021-02-14   54000
4        E005   Edward      Sales   38      M   2016-11-30   58000
5        E006    Fiona         HR   32      F   2019-09-05   50000
6        E007   George    Finance   45      M   2012-12-18   80000
7        E008   Hannah      Sales   30      F   2020-08-09   47000
8        E009      Ian         IT   27      M   2022-01-10   52000
9        E010    Julia    Finance   36      F   2017-06-25   70000

   Experience  Performance_Rating
0           4                   3
1           7                   4
2          10                   5
3           3                   3
4           8                   4
5           5                   4
6          13                   5
7           4                   3
8           2                   2
9           8                   4

In [47]:
df.groupby(["Gender","Department"])["Employee_ID"].count()

Gender  Department
F       Finance       1
        HR            2
        IT            1
        Sales         1
M       Finance       2
        IT            2
        Sales         1
Name: Employee_ID, dtype: int64

In [52]:
df.groupby("Department")["Performance_Rating"].agg("mean")

Department
Finance    4.666667
HR         3.500000
IT         3.000000
Sales      3.500000
Name: Performance_Rating, dtype: float64

In [54]:
df.groupby("Department").agg({"Age":"mean","Experience":"mean","Salary":"sum"})

                  Age  Experience  Salary
Department
Finance     40.666667   10.333333  222000
HR          30.500000    4.500000   98000
IT          30.000000    4.000000  171000
Sales       34.000000    6.000000  105000

True